# Generated by Django 4.0.4 on 2022-10-05 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('title2', models.CharField(default='', max_length=255)),
                ('description', models.CharField(default='', max_length=255)),
                ('desc_long', models.CharField(default='', max_length=255)),
                ('is_visible', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='artist',
            name='is_home',
        ),
        migrations.AddField(
            model_name='artist',
            name='about',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='artist',
            name='discord',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='artist',
            name='facebook',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='artist',
            name='instagram',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='artist',
            name='twitter',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='carousel',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.artist')),
            ],
        ),
    ]
